---
title: "EDUCATION INFORMATION"
author: "MRC/WITS-AGINCOURT UNIT STUDY AREA"
output: pdf_document
params:
  year: NA
  village: NA
header-includes:
- \usepackage{booktabs}
- \usepackage{sectsty} \sectionfont{\centering}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RODBC)
library(tidyverse)
library(gridExtra)

 name = "Chido"
 
  if (params$village == 1) {
    name = "Agincourt"
  } else if (params$village == 80) {
    name = "Original villages within the Agincourt Health and Demographic Surveillence Site "
  } else if (params$village == 90) {
    name = "All villages within the Agincourt Health and Demographic Surveillence Site"
  } else if (params$village == 2) {
    name = "Croquetlawn"
  } else if (params$village == 3) {
    name = "Cunningmore A"
  } else if (params$village == 4) {
    name = "Cunningmore B"
  } else if (params$village == 5) {
    name = "Huntington"
  } else if (params$village == 6) {
    name = "Ireagh A"
  } else if (params$village == 7) {
    name = "Ireagh B"
  } else if (params$village == 8) {
    name = "Justicia A"
  } else if (params$village == 9) {
    name = "Kildare A"
  } else if (params$village == 10) {
    name = "Kildare B"
  } else if (params$village == 11) {
    name = "Lillydale A"
  } else if (params$village == 12) {
    name = "Lillydale B"
  } else if (params$village == 13) {
    name = "Newington B"
  } else if (params$village == 14) {
    name = "Newington C"
  } else if (params$village == 15) {
    name = "Somerset A"
  } else if (params$village == 16) {
    name = "Xanthia"
  } else if (params$village == 21) {
    name = "Khaya Lami"
  } else if (params$village == 22) {
    name = "Croquet Lawn B"
  } else if (params$village == 23) {
    name = "Belfast"
  } else if (params$village == 24) {
    name = "Dumphries A"
  } else if (params$village == 25) {
    name = "Dumphries B"
  } else if (params$village == 26) {
    name = "Dumphries C"
  } else if (params$village == 27) {
    name = "Ireagh C"
  } else if (params$village == 28) {
    name = "Somerset C"
  } else if (params$village == 29) {
    name = "MP Stream"
  } else if (params$village == 30) {
    name = "Rolle C"
  } else if (params$village == 31) {
    name = "Kumani"
  } else {
    name = "Makaringe"
  }
# setup  ODBC connction to the cfb databse
con <- odbcDriverConnect("driver=SQL Server;server=DELL;database=CFB")
       sqlQuery(con,"select * from cfb..CurrentEdu") %>%
       filter(VillNo == params$village, Years == params$year) %>%
       select(Years, Age, PreSchool, Grade1to4, Grade5to7, Grade8to12, Incomplete_Tertiary, Complete_Tertiary, Total_Pop) %>%
      gather(Education_Level, Number, -c(Years, Age, Total_Pop) ) %>%
      select(Years, Age, Education_Level, Number, Total_Pop) -> currentedu
```


# `r name` in `r params$year`

```{r, echo=FALSE, warning= FALSE, out.width = "80%"}
currentedu$Education_Level <- factor(currentedu$Education_Level)
levels(currentedu$Education_Level) <- c("Complete tertiary","Grade 1 to 4","Grade 5 to 7","Grade 8 to 12","Incomplete tertiary","Pre School")
currentedu$Education_Level <- factor(currentedu$Education_Level, levels = c("Pre School","Grade 1 to 4","Grade 5 to 7","Grade 8 to 12","Incomplete tertiary","Complete tertiary"))


 currentedu %>%
   filter(Education_Level== "Pre School") %>%
   select(Age, Total_Pop) %>%
   distinct() -> m1
 
colnames(m1) <- c("Age","Number")
 
                     ggplot(data =currentedu, aes(x = factor(Age), y = Number)) +
                     geom_col(aes(fill= Education_Level)) +
                     geom_line(data = m1, aes(y =Number ,x= factor(Age), group = 1)) +
                     scale_fill_grey() +
                     theme_bw() +
                     labs(y ='Number of Students',
                          x = 'Age',
                          title= "Child Enrolment in Various Levels of School by Age group 1-21",
                          fill="Education Level\n"
                         ) +
                     theme(legend.title.align=0.5) +
                     theme(legend.box =  "horizontal",
                           text = element_text(family = "Bookman"),
                           title = element_text(color = "gray25"),
                           plot.caption = element_text(color = "gray30"),
                          plot.subtitle = element_text(size = 12))
```

```{r pressure, echo=FALSE,warning=FALSE, out.width= "90%"}

currentedu %>%
  filter(Age > 9 & Education_Level == "Grade 8 to 12") %>%
  dplyr::select(Age, Number,Total_Pop) %>%
  gather(Category,Value,-c(Age)) %>%
  mutate(Category =fct_relevel(Category,"Total_Pop","Number")) -> t1

levels(t1$Category) <- c("Total Population","Grade 8 to 12")

  ggplot(t1, aes(x = Age, y = Value, fill=Category)) +
  geom_area(stat="identity", position = "dodge") +
  ylab('Number of Students') +
  xlab('Age') +
  scale_fill_grey()+
  theme_bw() +
  theme(legend.title.align=0.5,
        legend.box =  "horizontal",
        text = element_text(family = "Bookman"),
        title = element_text(color = "gray25"),
        plot.caption = element_text(color = "gray30"),
        legend.text=element_text(size=8),
        legend.title = element_blank(),
        legend.position="bottom") +
  labs(title= "Village Youth in Grade 8 to 12",
       x = 'Age',
       y = 'Number of Students') -> p1

currentedu %>%
  filter(Age > 15 , Education_Level == "Incomplete tertiary") %>%
  select(Age, Number,Total_Pop) %>%
  gather(Category,Value,-c(Age)) %>%
  mutate(Category =fct_relevel(Category,"Total_Pop","Number")) -> t2
levels(t2$Category) <- c("Total Population","Tertiary")

  ggplot(t2, aes(x = Age, y = Value, fill=Category)) +
  geom_area(stat="identity", position = "dodge") +
  scale_fill_grey()+
  theme_bw() +
  theme(legend.title.align=0.5,
        legend.box =  "horizontal",
        text = element_text(family = "Bookman"),
        title = element_text(color = "gray25"),
        plot.caption = element_text(color = "gray30"),
        legend.text=element_text(size=8),
        legend.title = element_blank(),
        legend.position="bottom") +
  labs(title= "Village Youth in Tertiary",
       x = 'Age',
       y = 'Number of Students') -> p2

grid.arrange(p1, p2, ncol =2)
```